apiVersion: apps/v1
kind: Deployment
metadata:
name: devops-java-app
spec:
replicas: 1
selector:
matchLabels:
app: devops-java-app
template:
metadata:
labels:
app: devops-java-app
spec:
containers:
- name: devops-java-app
image: johnsharma24/apache-app:v1
ports:
- containerPort: 80

